import type { Project } from "@/types/content";

/**
 * ALL ENTRIES BELOW ARE SAMPLES. Replace with real projects and set isSample: false.
 * For real projects, add billBeforeInr and billAfterInr (monthly bills from the customer) when you have them.
 */
export const projects: Project[] = [
  {
    slug: "3kw-home-system-jp-nagar",
    title: "3 kW home system, JP Nagar",
    summary: "A terrace system sized to a family's monthly consumption, designed around a water tank and staircase shadow.",
    customerType: "Residential",
    location: { area: "JP Nagar", city: "Bengaluru", state: "Karnataka" },
    systemSizeKw: 3,
    roofType: "RCC",
    panels: "[Add panel brand, wattage and count]",
    inverter: "[Add inverter brand and model]",
    installedOn: "[Month YYYY]",
    estimatedMonthlySavingsInr: 2500,
    details: [
      "[Describe the roof, the challenge and how you solved it.]",
      "[Mention approvals handled, e.g. BESCOM net metering.]",
    ],
    image: { src: "/images/projects/project-1.svg", alt: "3 kW rooftop solar system on a home in JP Nagar" },
    gallery: [{ src: "/images/projects/project-1.svg", alt: "Installed panels on terrace" }],
    testimonial: { quote: "[Sample testimonial. Replace with a real customer quote.]", name: "Customer Name", role: "Homeowner" },
    isSample: true,
  },
  {
    slug: "10kw-apartment-bannerghatta-road",
    title: "10 kW apartment common-area system, Bannerghatta Road",
    summary: "Rooftop solar to offset lift, lighting and pump loads for an apartment association.",
    customerType: "Residential",
    location: { area: "Bannerghatta Road", city: "Bengaluru", state: "Karnataka" },
    systemSizeKw: 10,
    roofType: "RCC",
    panels: "[Add panel brand, wattage and count]",
    inverter: "[Add inverter brand and model]",
    installedOn: "[Month YYYY]",
    estimatedMonthlySavingsInr: 8000,
    details: ["[Describe the project, roof access and approvals.]"],
    image: { src: "/images/projects/project-2.svg", alt: "Rooftop solar on an apartment building" },
    gallery: [{ src: "/images/projects/project-2.svg", alt: "Array on apartment roof" }],
    isSample: true,
  },
  {
    slug: "25kw-commercial-whitefield",
    title: "25 kW commercial rooftop, Whitefield",
    summary: "An office-building system matched to weekday daytime load.",
    customerType: "Commercial",
    location: { area: "Whitefield", city: "Bengaluru", state: "Karnataka" },
    systemSizeKw: 25,
    roofType: "RCC",
    panels: "[Add panel brand, wattage and count]",
    inverter: "[Add inverter brand and model]",
    installedOn: "[Month YYYY]",
    estimatedMonthlySavingsInr: 20000,
    details: ["[Describe the load profile, design and results.]"],
    image: { src: "/images/projects/project-3.svg", alt: "Commercial rooftop solar array" },
    gallery: [{ src: "/images/projects/project-3.svg", alt: "Commercial array" }],
    isSample: true,
  },
  {
    slug: "50kw-factory-roof-tumakuru",
    title: "50 kW factory roof, Tumakuru",
    summary: "A sheet-roof industrial system with structure designed for wind load.",
    customerType: "Industrial",
    location: { city: "Tumakuru", state: "Karnataka" },
    systemSizeKw: 50,
    roofType: "Sheet",
    panels: "[Add panel brand, wattage and count]",
    inverter: "[Add inverter brand and model]",
    installedOn: "[Month YYYY]",
    estimatedMonthlySavingsInr: 40000,
    details: ["[Describe the roof assessment, structure and commissioning.]"],
    image: { src: "/images/projects/project-4.svg", alt: "Solar panels on a factory sheet roof" },
    gallery: [{ src: "/images/projects/project-4.svg", alt: "Factory roof array" }],
    isSample: true,
  },
];
